GOOGLE_AI_STUDIO_API_KEY = "AIzaSyDM8s5NW-GnVlnVulguFuft2uDqitt6CpI"
YOUTUBE_API_KEY1 = "AIzaSyBTrhS9Uyi6_P6UFCsmSyz-p_9fsI6tkDI"
YOUTUBE_API_KEY2 = "your_youtube_api_key_2"
YOUTUBE_API_KEY3 = "your_youtube_api_key_3"
YOUTUBE_API_KEY4 = "your_youtube_api_key_4"

# SERP API 키 (뉴스 검색용)
SERP_API_KEY1 = "your_serpapi_key_1"
SERP_API_KEY2 = "your_serpapi_key_2"

# Apify API 키 (YouTube 자막 보조용)
APIFY_API_KEY = "your_apify_key"